name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker registry (Docker Hub example)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker images
      - name: Build frontend image
        run: docker build -t hvmil/frontend:latest ./frontend

      - name: Build backend image
        run: docker build -t hvmil/backend:latest ./backend

      # Step 5: Push Docker images to registry
      - name: Push frontend image
        run: docker push hvmil/frontend:latest

      - name: Push backend image
        run: docker push hvmil/backend:latest
